image: node:8.12.0

pages:
  script:
  - npm install
  - npm install gatsby-cli
  - node_modules/.bin/gatsby build
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
  only:
  - master
